### ISSUE TITLE
tow for Cartrailer

### ISSUE THREAD

**Issue by XyCoDeLiC** [Deziel0495/TowScript#2]
First of, let me just say, Great Script! Works awesomely on my ESX server. I don't run a trainer on my server, so I added the cartrailer to the tow script and it does work somewhat, only problem is that it attaches the cars nose up. Is there any way I can flip the car forwards by 90 degrees to make it stand on its wheels on the trailer? Thanks in advance for your time. Have a great day and keep up the outstanding work.

**Comment by royalko** [comment]
did you fix this?

**Comment by XyCoDeLiC** [comment]
The new Car Trailer that came out actually fixes that problem. I have also managed to change the script to be able to load Bikes on Trucks.
